apiVersion: apps/v1
kind: Deployment
metadata:
  name: aijazmeer-eta-deploy
  labels:
    app: aijazmeer-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aijazmeer-eta-app
  template:
    metadata:
      labels:
        app: aijazmeer-eta-app
    spec:
      containers:
      - name: aijazmeer-eta-container
        image: aijazmeereta/aijazmeer-eta-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aijazmeer-eta-np-service
  labels:
    app: aijazmeer-eta-app
spec:
  selector:
    app: aijazmeer-eta-app

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
